student:
  name: Tom
  age: 26
spring:
  profiles:
    active: test
  datasource:
    url: jdbc:mysql://127.0.0.1/hh?characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
          hbm2ddl:
            auto: update

