server:
  port: 8081
student:
  name: Tom
  age: 26
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/hh?characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
